### ISSUE TITLE
depreciated PIL vs pillow and fatal error loading heic file

### ISSUE THREAD

**Issue by saltorico** [Anant-mishra1729/heif-to-image-converter#2]
Requirements.txt didn't seem to be complete. Installed pillow and rewired the import from PIL as it's depreciated. Still got error message

  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pyheif/reader.py", line 402, in _read_heif_image
    p_options.ignore_transformations = int(not heif_file.apply_transformations)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ffi.error: struct heif_decoding_options: wrong total size (cdef says 48, but C compiler says 72). fix it or use "...;" as the last field in the cdef for struct heif_decoding_options to make it flexible

**Comment by Anant-mishra1729** [comment]
This was a bug in pyheif. I've switched the script to pillow-heif now. Thanks for reporting the issue.
